#pragma once

// Pubg Mobile Battelgrounds (2.7.0-64BIT) SDK Generated By @hhamk2 
// 𝚃𝚎𝚕𝚎𝚐𝚛𝚊𝚖 -: @SANSERO_MOD_1
namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_TransColumns_type.BP_STRUCT_TransColumns_type
// 0x0020
struct FBP_STRUCT_TransColumns_type
{
	struct FString                                     Columns_0_47AC24714CA709ABE62AB2B97B02C861;               // 0x0000(0x0010) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     Table_1_B0FEB2B8486D4078687135A2F1589ADF;                 // 0x0010(0x0010) (Edit, BlueprintVisible, ZeroConstructor)
};

}

