#pragma once

// Pubg Mobile Battelgrounds (2.7.0-64BIT) SDK Generated By @hhamk2 
// 𝚃𝚎𝚕𝚎𝚐𝚛𝚊𝚖 -: @SANSERO_MOD_1
namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// ScriptStruct HiggsBoson.Bazi
// 0x0018
struct FBazi
{
	int                                                Adam;                                                     // 0x0000(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x4];                                       // 0x0004(0x0004) MISSED OFFSET
	TArray<float>                                      Array;                                                    // 0x0008(0x0010) (ZeroConstructor)
};

// ScriptStruct HiggsBoson.PatchPoint
// 0x000C
struct FPatchPoint
{
	int                                                Offset;                                                   // 0x0000(0x0004) (ZeroConstructor, IsPlainOldData)
	uint32_t                                           Old;                                                      // 0x0004(0x0004) (ZeroConstructor, IsPlainOldData)
	uint32_t                                           New;                                                      // 0x0008(0x0004) (ZeroConstructor, IsPlainOldData)
};

}

