#pragma once

// Pubg Mobile Battelgrounds (2.7.0-64BIT) SDK Generated By @hhamk2 
// 𝚃𝚎𝚕𝚎𝚐𝚛𝚊𝚖 -: @SANSERO_MOD_1
namespace SDK
{
//---------------------------------------------------------------------------
//Enums
//---------------------------------------------------------------------------

// Enum QuantumDevKit.EQuantumFirebaseRemoteConfigStatus
enum class EQuantumFirebaseRemoteConfigStatus : uint8_t
{
	EQuantumFirebaseRemoteConfigStatus__kUnfetched = 0,
	EQuantumFirebaseRemoteConfigStatus__kFetchedSuccessfully = 1,
	EQuantumFirebaseRemoteConfigStatus__kFetchedFailed = 2,
	EQuantumFirebaseRemoteConfigStatus__EQuantumFirebaseRemoteConfigStatus_MAX = 3
};



}

