#pragma once

// Pubg Mobile Battelgrounds (2.7.0-64BIT) SDK Generated By @hhamk2 
// 𝚃𝚎𝚕𝚎𝚐𝚛𝚊𝚖 -: @SANSERO_MOD_1
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function Reconnect_BP.Reconnect_BP_C.Construct
struct UReconnect_BP_C_Construct_Params
{
};

// Function Reconnect_BP.Reconnect_BP_C.ExecuteUbergraph_Reconnect_BP
struct UReconnect_BP_C_ExecuteUbergraph_Reconnect_BP_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

