std::string JSON_ITEMSSKL = "[\n"
                         "  {\n"
                         "    \"Category\": \"火力对决物品\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 107006,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"RPG\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 107093,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"AT4-A激光导弹\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 107095,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"M202四连火箭筒\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 107098,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"MGL榴弹发射器\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 107096,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"M79短管榴弹发射器\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 107097,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"M79榴弹发射器\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 107099,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"M3E1-A导弹\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 107911,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"M3E1-B导弹\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 105003,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"M134重机枪\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 602026,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"空袭定位仪\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 403702,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"防爆服\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 602038,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"无人机终端\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"极限追猎物品\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 3006001,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"纳米晶体\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 61010,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"召回信标\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 3006002,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"动力装甲蓝图\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 4181001,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"外骨骼手臂\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 4191001,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"外骨骼胸甲\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 4201001,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"外骨骼腿甲\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"特殊物品\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 605008,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"防爆盾\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106009,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"信号枪\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 602036,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"尖刺陷阱\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 602045,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"粘性炸弹\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 403045,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"吉利服\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 403187,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"吉利服(沙漠)\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 403989,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"吉利服(雪地)\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 403990,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"吉利服(深棕)\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"XT武器\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 101901,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"AKM-XT\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101903,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"SCAR-XT\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101908,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"M762-XT\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 102901,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"UZI-XT\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 102903,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"Vector-XT\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103902,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"M24-XT\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106908,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"VZ61-XT\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"投掷物\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 602005,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"苹果\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 602001,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"震撼弹\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 602002,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"烟雾弹\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 602003,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"燃烧瓶\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 602004,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"手榴弹\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"步枪\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 101001,\n"
                         "        \"itemClass\": \"BP_Rifle_AKM_Wrapper_C_1\",\n"
                         "        \"itemName\": \"AKM\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101002,\n"
                         "        \"itemClass\": \"BP_Rifle_M16A4_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M16A4\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101003,\n"
                         "        \"itemClass\": \"BP_Rifle_SCAR_Wrapper_C_1\",\n"
                         "        \"itemName\": \"SCAR-L\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101004,\n"
                         "        \"itemClass\": \"BP_Rifle_M416_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M416\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101005,\n"
                         "        \"itemClass\": \"BP_Rifle_Groza_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Groza\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101006,\n"
                         "        \"itemClass\": \"BP_Rifle_AUG_Wrapper_C_1\",\n"
                         "        \"itemName\": \"AUG\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101007,\n"
                         "        \"itemClass\": \"BP_Rifle_QBZ_Wrapper_C_1\",\n"
                         "        \"itemName\": \"QBZ\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101008,\n"
                         "        \"itemClass\": \"BP_Rifle_M762_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M762\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101009,\n"
                         "        \"itemClass\": \"BP_Rifle_Mk47_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Mk47\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101010,\n"
                         "        \"itemClass\": \"BP_Rifle_G36_Wrapper_C_1\",\n"
                         "        \"itemName\": \"G36C\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101100,\n"
                         "        \"itemClass\": \"BP_Rifle_FAMAS_Wrapper_C_1\",\n"
                         "        \"itemName\": \"FAMAS\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 105001,\n"
                         "        \"itemClass\": \"BP_Other_M249_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M249\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 105010,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"MG3\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 105002,\n"
                         "        \"itemClass\": \"BP_Other_DP28_Wrapper_C_1\",\n"
                         "        \"itemName\": \"DP-28\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"冲锋枪\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 102001,\n"
                         "        \"itemClass\": \"BP_MachineGun_Uzi_Wrapper_C_1\",\n"
                         "        \"itemName\": \"UZI\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 102002,\n"
                         "        \"itemClass\": \"BP_MachineGun_UMP9_Wrapper_C_1\",\n"
                         "        \"itemName\": \"UMP45\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 102003,\n"
                         "        \"itemClass\": \"BP_MachineGun_Vector_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Vector\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 102004,\n"
                         "        \"itemClass\": \"BP_MachineGun_TommyGun_Wrapper_C_1\",\n"
                         "        \"itemName\": \"汤姆逊\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 102005,\n"
                         "        \"itemClass\": \"BP_MachineGun_PP19_Wrapper_C_1\",\n"
                         "        \"itemName\": \"野牛冲锋枪\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 102007,\n"
                         "        \"itemClass\": \"BP_MachineGun_MP5K_Wrapper_C_1\",\n"
                         "        \"itemName\": \"蝎式手枪\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"狙击枪\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 103001,\n"
                         "        \"itemClass\": \"BP_Sniper_Kar98k_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Kar98K\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103002,\n"
                         "        \"itemClass\": \"BP_Sniper_M24_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M24\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103003,\n"
                         "        \"itemClass\": \"BP_Sniper_AWM_Wrapper_C_1\",\n"
                         "        \"itemName\": \"AWM\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103004,\n"
                         "        \"itemClass\": \"BP_Sniper_SKS_Wrapper_C_1\",\n"
                         "        \"itemName\": \"SKS\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103005,\n"
                         "        \"itemClass\": \"BP_Sniper_VSS_Wrapper_C_1\",\n"
                         "        \"itemName\": \"VSS\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103006,\n"
                         "        \"itemClass\": \"BP_Sniper_Mini14_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Mini14\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103007,\n"
                         "        \"itemClass\": \"BP_WEP_Mk14_Pickup_C_1\",\n"
                         "        \"itemName\": \"Mk14\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103008,\n"
                         "        \"itemClass\": \"BP_Sniper_Win94_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Win94\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103009,\n"
                         "        \"itemClass\": \"BP_Sniper_SLR_Wrapper_C_1\",\n"
                         "        \"itemName\": \"SLR\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103010,\n"
                         "        \"itemClass\": \"BP_Sniper_QBU_Wrapper_C_1\",\n"
                         "        \"itemName\": \"QBU\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103011,\n"
                         "        \"itemClass\": \"BP_Sniper_Mosin_Wrapper_C_1\",\n"
                         "        \"itemName\": \"莫幸纳甘\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103100,\n"
                         "        \"itemClass\": \"BP_Sniper_MK12_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Mk12\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"霰弹枪\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 104001,\n"
                         "        \"itemClass\": \"BP_ShotGun_S686_Wrapper_C_1\",\n"
                         "        \"itemName\": \"S686\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 104002,\n"
                         "        \"itemClass\": \"BP_ShotGun_S1897_Wrapper_C_1\",\n"
                         "        \"itemName\": \"S1897\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 104003,\n"
                         "        \"itemClass\": \"BP_ShotGun_S12K_Wrapper_C_1\",\n"
                         "        \"itemName\": \"S12K\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 104004,\n"
                         "        \"itemClass\": \"BP_ShotGun_DP12_Wrapper_C_1\",\n"
                         "        \"itemName\": \"DP12\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 104101,\n"
                         "        \"itemClass\": \"BP_ShotGun_M1014_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M1014散弹枪\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106006,\n"
                         "        \"itemClass\": \"BP_ShotGun_SawedOff_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Sawed-off\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"手枪\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 106001,\n"
                         "        \"itemClass\": \"BP_Pistol_P92_Wrapper_C_1\",\n"
                         "        \"itemName\": \"P92\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106002,\n"
                         "        \"itemClass\": \"BP_Pistol_P1911_Wrapper_C_1\",\n"
                         "        \"itemName\": \"P1911\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106003,\n"
                         "        \"itemClass\": \"BP_Pistol_R1895_Wrapper_C_1\",\n"
                         "        \"itemName\": \"R1895\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106004,\n"
                         "        \"itemClass\": \"BP_Pistol_P18C_Wrapper_C_1\",\n"
                         "        \"itemName\": \"P18C\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106005,\n"
                         "        \"itemClass\": \"BP_Pistol_R45_Wrapper_C_1\",\n"
                         "        \"itemName\": \"R45\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106008,\n"
                         "        \"itemClass\": \"BP_Pistol_Vz61_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Vz61\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106010,\n"
                         "        \"itemClass\": \"BP_Pistol_DesertEagle_Wrapper_C_1\",\n"
                         "        \"itemName\": \"沙漠之鹰\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"其他\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 107001,\n"
                         "        \"itemClass\": \"BP_Other_CrossBow_Wrapper_C_1\",\n"
                         "        \"itemName\": \"弩\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"近战\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 108001,\n"
                         "        \"itemClass\": \"BP_WEP_Machete_Pickup_C_1\",\n"
                         "        \"itemName\": \"砍刀\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 108002,\n"
                         "        \"itemClass\": \"BP_WEP_Cowbar_Pickup_C_1\",\n"
                         "        \"itemName\": \"撬棍\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 108003,\n"
                         "        \"itemClass\": \"BP_WEP_Sickle_Pickup_C_1\",\n"
                         "        \"itemName\": \"镰刀\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 108004,\n"
                         "        \"itemClass\": \"BP_WEP_Pan_Pickup_C_1\",\n"
                         "        \"itemName\": \"平底锅\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"配件\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 201052,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"狙击枪枪口抑制器\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201053,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"步枪枪口抑制器\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201054,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"冲锋枪枪口抑制器\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201001,\n"
                         "        \"itemClass\": \"BP_QK_Choke_Pickup_C_1\",\n"
                         "        \"itemName\": \"托腮板\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201002,\n"
                         "        \"itemClass\": \"BP_QK_Mid_Compensator_Pickup_C_1\",\n"
                         "        \"itemName\": \"冲锋枪补偿器\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201003,\n"
                         "        \"itemClass\": \"BP_QK_Sniper_Compensator_Pickup_C_1\",\n"
                         "        \"itemName\": \"狙击枪补偿器\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201004,\n"
                         "        \"itemClass\": \"BP_QK_Mid_FlashHider_Pickup_C_1\",\n"
                         "        \"itemName\": \"冲锋枪消焰器\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201005,\n"
                         "        \"itemClass\": \"BP_QK_Sniper_FlashHider_Pickup_C_1\",\n"
                         "        \"itemName\": \"狙击枪消焰器\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201006,\n"
                         "        \"itemClass\": \"BP_QK_Mid_Suppressor_Pickup_C_1\",\n"
                         "        \"itemName\": \"冲锋枪消音器\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201007,\n"
                         "        \"itemClass\": \"BP_QK_Sniper_Suppressor_Pickup_C_1\",\n"
                         "        \"itemName\": \"狙击枪消音器\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201009,\n"
                         "        \"itemClass\": \"BP_QK_Large_Compensator_Pickup_C_1\",\n"
                         "        \"itemName\": \"步枪补偿器\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201010,\n"
                         "        \"itemClass\": \"BP_QK_Large_FlashHider_Pickup_C_1\",\n"
                         "        \"itemName\": \"步枪消焰器\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201011,\n"
                         "        \"itemClass\": \"BP_QK_Large_Suppressor_Pickup_C_1\",\n"
                         "        \"itemName\": \"步枪消音器\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201012,\n"
                         "        \"itemClass\": \"BP_QK_DuckBill_Pickup_C_1\",\n"
                         "        \"itemName\": \"鸭嘴枪口\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 202001,\n"
                         "        \"itemClass\": \"BP_WB_Angled_Pickup_C_1\",\n"
                         "        \"itemName\": \"直角握把\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 202002,\n"
                         "        \"itemClass\": \"BP_WB_Vertical_Pickup_C_1\",\n"
                         "        \"itemName\": \"垂直握把\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 202004,\n"
                         "        \"itemClass\": \"BP_WB_LightGrip_Pickup_C_1\",\n"
                         "        \"itemName\": \"轻型握把\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 202005,\n"
                         "        \"itemClass\": \"BP_WB_HalfGrip_Pickup_C_1\",\n"
                         "        \"itemName\": \"半径握把\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 202006,\n"
                         "        \"itemClass\": \"BP_WB_ThumbGrip_Pickup_C_1\",\n"
                         "        \"itemName\": \"拇指握把\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 202007,\n"
                         "        \"itemClass\": \"BP_WB_Lasersight_Pickup_C_1\",\n"
                         "        \"itemName\": \"激光瞄准器\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203001,\n"
                         "        \"itemClass\": \"BP_MZJ_HD_Pickup_C_1\",\n"
                         "        \"itemName\": \"红点\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203002,\n"
                         "        \"itemClass\": \"BP_MZJ_QX_Pickup_C_1\",\n"
                         "        \"itemName\": \"全息\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203003,\n"
                         "        \"itemClass\": \"BP_MZJ_2X_Pickup_C_1\",\n"
                         "        \"itemName\": \"2倍镜\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203004,\n"
                         "        \"itemClass\": \"BP_MZJ_4X_Pickup_C_1\",\n"
                         "        \"itemName\": \"4倍镜\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203005,\n"
                         "        \"itemClass\": \"BP_MZJ_8X_Pickup_C_1\",\n"
                         "        \"itemName\": \"8倍镜\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203014,\n"
                         "        \"itemClass\": \"BP_MZJ_3X_Pickup_C_1\",\n"
                         "        \"itemName\": \"3倍镜\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203015,\n"
                         "        \"itemClass\": \"BP_MZJ_6X_Pickup_C_1\",\n"
                         "        \"itemName\": \"6倍镜\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203018,\n"
                         "        \"itemClass\": \"BP_MZJ_SideRMR_Pickup_C_1\",\n"
                         "        \"itemName\": \"侧边瞄准镜\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204014,\n"
                         "        \"itemClass\": \"BP_ZDD_Sniper_Pickup_C_1\",\n"
                         "        \"itemName\": \"子弹袋\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 205001,\n"
                         "        \"itemClass\": \"BP_QT_UZI_Pickup_C_1\",\n"
                         "        \"itemName\": \"枪托(uzi)\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 205002,\n"
                         "        \"itemClass\": \"BP_QT_A_Pickup_C_1\",\n"
                         "        \"itemName\": \"战术枪托\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 205003,\n"
                         "        \"itemClass\": \"BP_QT_Sniper_Pickup_C_1\",\n"
                         "        \"itemName\": \"托腮板\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 205004,\n"
                         "        \"itemClass\": \"BP_ZDD_Crossbow_Q_Pickup_C_1\",\n"
                         "        \"itemName\": \"箭袋\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"弹夹\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 204016,\n"
                         "        \"itemClass\": \"BP_DJ_Mid_Q_Pickup_C_1\",\n"
                         "        \"itemName\": \"步枪快扩弹鼓\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204051,\n"
                         "        \"itemClass\": \"KL NIKE MOD\",\n"
                         "        \"itemName\": \"步枪弹鼓\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204004,\n"
                         "        \"itemClass\": \"BP_DJ_Mid_E_Pickup_C_1\",\n"
                         "        \"itemName\": \"冲锋枪扩容弹夹\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204005,\n"
                         "        \"itemClass\": \"BP_DJ_Mid_Q_Pickup_C_1\",\n"
                         "        \"itemName\": \"冲锋枪快速弹夹\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204006,\n"
                         "        \"itemClass\": \"BP_DJ_Mid_EQ_Pickup_C_1\",\n"
                         "        \"itemName\": \"冲锋枪快速扩容弹夹\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204007,\n"
                         "        \"itemClass\": \"BP_DJ_Sniper_E_Pickup_C_1\",\n"
                         "        \"itemName\": \"狙击枪扩容弹夹\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204008,\n"
                         "        \"itemClass\": \"BP_DJ_Sniper_Q_Pickup_C_1\",\n"
                         "        \"itemName\": \"狙击枪快速弹夹\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204009,\n"
                         "        \"itemClass\": \"BP_DJ_Sniper_EQ_Pickup_C_1\",\n"
                         "        \"itemName\": \"狙击枪快速扩容弹夹\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204011,\n"
                         "        \"itemClass\": \"BP_DJ_Large_E_Pickup_C_1\",\n"
                         "        \"itemName\": \"步枪扩容弹夹\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204012,\n"
                         "        \"itemClass\": \"BP_DJ_Large_Q_Pickup_C_1\",\n"
                         "        \"itemName\": \"步枪快速弹夹\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204013,\n"
                         "        \"itemClass\": \"BP_DJ_Large_EQ_Pickup_C_1\",\n"
                         "        \"itemName\": \"步枪快速扩容弹夹\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"子弹\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 301001,\n"
                         "        \"itemClass\": \"BP_Ammo_9mm_Pickup_C_1\",\n"
                         "        \"itemName\": \"9mm\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 302001,\n"
                         "        \"itemClass\": \"BP_Ammo_762mm_Pickup_C_1\",\n"
                         "        \"itemName\": \"7.62mm\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 303001,\n"
                         "        \"itemClass\": \"BP_Ammo_556mm_Pickup_C_1\",\n"
                         "        \"itemName\": \"5.56mm\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 304001,\n"
                         "        \"itemClass\": \"BP_Ammo_12Guage_Pickup_C_1\",\n"
                         "        \"itemName\": \"12口径\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 305001,\n"
                         "        \"itemClass\": \"BP_Ammo_45ACP_Pickup_C_1\",\n"
                         "        \"itemName\": \".45子弹\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 306001,\n"
                         "        \"itemClass\": \"BP_Ammo_300Magnum_Pickup_C_1\",\n"
                         "        \"itemName\": \"300马格南\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 307001,\n"
                         "        \"itemClass\": \"BP_Ammo_Bolt_Pickup_C_1\",\n"
                         "        \"itemName\": \"弩箭\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"背包\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 501001,\n"
                         "        \"itemClass\": \"PickUp_BP_Bag_Lv1_C_1\",\n"
                         "        \"itemName\": \"1级包\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 501002,\n"
                         "        \"itemClass\": \"PickUp_BP_Bag_Lv2_C_1\",\n"
                         "        \"itemName\": \"2级包\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 501006,\n"
                         "        \"itemClass\": \"PickUp_BP_Bag_Lv3_B_C_1\",\n"
                         "        \"itemName\": \"3级包\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"头盔\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 502001,\n"
                         "        \"itemClass\": \"PickUp_BP_Helmet_Lv1_C_1\",\n"
                         "        \"itemName\": \"1级头\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 502002,\n"
                         "        \"itemClass\": \"PickUp_BP_Helmet_Lv2_C_1\",\n"
                         "        \"itemName\": \"2级头\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 502003,\n"
                         "        \"itemClass\": \"PickUp_BP_Helmet_Lv3_C_1\",\n"
                         "        \"itemName\": \"3级头\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"护甲\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 503001,\n"
                         "        \"itemClass\": \"PickUp_BP_Armor_Lv1_C_1\",\n"
                         "        \"itemName\": \"1级甲\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 503002,\n"
                         "        \"itemClass\": \"PickUp_BP_Armor_Lv2_C_1\",\n"
                         "        \"itemName\": \"2级甲\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 503003,\n"
                         "        \"itemClass\": \"PickUp_BP_Armor_Lv3_C_1\",\n"
                         "        \"itemName\": \"3级甲\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"药品\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 601001,\n"
                         "        \"itemClass\": \"Drink_Pickup_C_1\",\n"
                         "        \"itemName\": \"能量饮料\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601002,\n"
                         "        \"itemClass\": \"Injection_Pickup_C_1\",\n"
                         "        \"itemName\": \"肾上腺素\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601003,\n"
                         "        \"itemClass\": \"Pills_Pickup_C_1\",\n"
                         "        \"itemName\": \"止痛药\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601004,\n"
                         "        \"itemClass\": \"Bandage_Pickup_C_1\",\n"
                         "        \"itemName\": \"绷带\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601005,\n"
                         "        \"itemClass\": \"Firstaid_Pickup_C_1\",\n"
                         "        \"itemName\": \"急救包\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601006,\n"
                         "        \"itemClass\": \"FirstAidbox_Pickup_C_1\",\n"
                         "        \"itemName\": \"医疗箱\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  }\n"
                         "]";